image:https://github.com/kubewarden/community/blob/main/badges/kubewarden-policies.svg[Kubewarden Policy Repository, link=https://github.com/kubewarden/community/blob/main/REPOSITORIES.md#policy-scope]
image:https://img.shields.io/badge/status-stable-brightgreen?style=for-the-badge[Stable, link=https://github.com/kubewarden/community/blob/main/REPOSITORIES.md#stable]

== harvester-restricted-network

This policy guards against harvester creating a network for a restricted VLAN in unauthorized namespaces.

=== Settings

|===
| Field | Description

| namespaceVLANBindings

map[string, link:#settingsVLANBinding[Namespace VLAN Binding]] | A map of namespace VLAN bindings.
|===

[[settingsVLANBinding]]
==== Namespace VLAN Binding

|===
| Field | Description

| namespaces

string | The namespace.

| vlan

int | The VLAN for the Harvester VM Network.
|===

=== Specifications

1. All bound namespaces must use their respective bound VLANs.
2. All bound VLANs must use their respective bound namespaces.
3. Any namespace or VLAN that isn't bound, is unrestricted.

=== Example

[source, yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: restricted-network-vm-policy-1
spec:
  module: registry://ghcr.io/suse/openplatform-kubewarden-policies/harvester-restricted-network-vm:latest
  rules:
    - apiGroups: ["kubevirt.io"]
      apiVersions: ["v1"]
      resources: ["virtualmachines"]
      operations: ["CREATE", "UPDATE"]
  settings:
    namespaceNetworkBindings:
      - namespace: test-restricted-1-network-1
        network:  test-restricted-1-network-1/network-1
      - namespace: test-restricted-2-network-1
        network:  test-restricted-1-network-1/network-1
      - namespace: test-restricted-3-network-3
        network:  test-restricted-3-network-3/network-3
  mutating: false
  policyServer: default
----

The following examples are with the example policy above, with a random non-restricted VLAN being 100.

|===
| namespace | VLAN | Result

| test-restricted-1-network-1 | 42      | ALLOW
| test-restricted-2-network-1 | 1337    | ALLOW
| random-namespace            | 100     | ALLOW
| test-restricted-1-network-1 | 1337    | REJECT
| test-restricted-2-network-2 | 42      | REJECT
| random-namespace            | 42      | REJECT
| random-namespace            | 1337    | REJECT
| test-restricted-1-network-1 | 100     | REJECT
| test-restricted-2-network-2 | 100     | REJECT
|===
