image:https://github.com/kubewarden/community/blob/main/badges/kubewarden-policies.svg[Kubewarden Policy Repository, link=https://github.com/kubewarden/community/blob/main/REPOSITORIES.md#policy-scope]
image:https://img.shields.io/badge/status-stable-brightgreen?style=for-the-badge[Stable, link=https://github.com/kubewarden/community/blob/main/REPOSITORIES.md#stable]

== harvester-restricted-network

This policy guards against VMs attaching PCI Devices (e.g., GPUs) without permission.

=== Settings

|===
| Field | Description

| namespaceDeviceBindings

map[string, link:#settingsDeviceBinding[Namespace Device Binding]] | A map of Harvester PCI Device bindings.
|===

[[settingsDeviceBinding]]
==== Namespace Device Binding

|===
| Field | Description

| namespaces

string | The namespace.

| device

string | The ID of the PCI device.
|===

=== Specifications

1. You should be able to create a VM without a PCI Device
2. You should not be able to bind a VM to a PCI Device not allocated to its namespace.

=== Example

[source, yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: harvester-pci-policy-1
spec:
  module: harbor.op-prg2-0-dev-ingress.op.suse.org/op-portal/kubewarden-policy:20
  rules:
    - apiGroups: ["kubevirt.io"]
      apiVersions: ["v1"]
      resources: ["virtualmachines"]
      operations: ["CREATE", "UPDATE"]
  settings:
    namespaceDeviceBindings:
      - namespace: test-ns-1
        device:  tekton27a-000001010
      - namespace: test-ns-2
        device:  tekton27b-000001010
  mutating: false  # or true if your policy mutates resources
  policyServer: default
----

|===
| namespace | Device | Result

| test-ns-1        | tekton27a-000001010 | ALLOW
| test-ns-2        | tekton27b-000001010 | ALLOW
| test-ns-1        | tekton27b-000001010 | REJECT
| test-ns-2        | tekton27a-000001010 | REJECT
| random-namespace | tekton27a-000001010 | REJECT
| random-namespace | tekton27b-000001010 | REJECT
|===
